version: "3.8"
services:

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=cryptobot
    ports:
      - "6379:6379"

  redis-slave:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=cryptobot
      - REDIS_PASSWORD=cryptobot
    ports:
      - "6378:6379"
    depends_on:
      - redis

  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_PASSWORD=cryptobot
    depends_on:
      - redis
      - redis-slave
    ports:
      - "26379:26379"
